=== ForestVixius/AffichageFormulaireXSL/DTD.dtd
<!ELEMENT formulaire ((composant | liste | boutonGroupe)*)>
	 <!ELEMENT liste (label, element+,(x, y)?, largeur?)>
			<!ATTLIST liste id ID #REQUIRED
									type  (int | char | boolean | String | double) #REQUIRED>
			<!ELEMENT element     (#PCDATA)>
			
	 <!ELEMENT boutonGroupe (label, (checkBox+ | boutonRadio*), (x, y)?, largeur?)>
			<!ATTLIST boutonGroupe id ID   #REQUIRED
					  type (int | char | boolean | String | double) #REQUIRED>
			<!ELEMENT checkBox        (#PCDATA)>
			<!ELEMENT boutonRadio     (#PCDATA)>
			<!ATTLIST boutonRadio ordre CDATA #REQUIRED>
			
	 <!ELEMENT composant (label, (x, y)?, largeur?)>
			<!ATTLIST composant id ID #REQUIRED
					  compo (champDeTexte | tableau) #REQUIRED
					  type  (int | char | boolean | String | double) #REQUIRED>
			 
			<!ELEMENT label     (#PCDATA)>
			<!ELEMENT posX      (#PCDATA)>
			<!ELEMENT posY      (#PCDATA)>
			<!ELEMENT largeur   (#PCDATA)>

=== ForestVixius/AffichageFormulaireXSL/formulaire.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="formulaire.xsl"?>

<!DOCTYPE formulaire SYSTEM "DTD.dtd">

<formulaire>

    <boutonGroupe id="c1" type="String">
        <label>Fruit</label>
        <checkBox>Pomme</checkBox>
        <checkBox>Poire</checkBox>
        <checkBox>Fraise</checkBox>
    </boutonGroupe>
    
    <liste id="c2" type="String">
        <label>Pays</label>
        <element>France</element>
        <element>Antigua Barbuda</element>
    </liste>
    
    <composant id="c3" compo="champDeTexte" type="String">
        <label>Prénom</label>
    </composant>

    <boutonGroupe id="c4" type="String">
        <label>Sexe</label>
        <boutonRadio>Homme</boutonRadio>
        <boutonRadio>Femme</boutonRadio>
        <boutonRadio>Autre</boutonRadio>
    </boutonGroupe>

    <tableau id="c5" type="int">
        <label>Tableau</label>
        <nbLignes>5</nbLignes>
        <nbColonnes>5</nbColonnes>
    </tableau>

    <calendrier id="c6">
        <label>Calendrier</label>
    </calendrier>

    <composant id="c7" compo="caseACocher" type="boolean">
        <label>Rester connecté ?</label>
    </composant>
    
</formulaire>
